[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "LARIMER County Total Population"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Total Population"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

[Data 1.1]

TSID = "LARIMER.DOLA.Population.Year"
TSAlias = "LARIMER-population"

[Data 1.2]

TSID = "LARIMER.DOLA.Population.Year.filled"
TSAlias = "LARIMER-population-filled"
