[Product]

ProductType = "Graph"
TotalWidth = "600"
TotalHeight = "400"
MainTitleString = "Swink Municipality Total Population"
SubTitleString = "Source:  DOLA (2021 refresh)"

[SubProduct 1]

GraphType = "Line"
LeftYAxisTitlePosition = "LeftOfAxis"
LeftYAxisTitleRotation = "270"
LeftYAxisTitleString = "Total Population"
RightYAxisGraphType = "None"
RightYAxisIgnoreUnits = "false"
LayoutYPercent = ""

[Data 1.1]

Color = "0x0000ff"
GraphType = "Line"
LineWidth = 2
TSID = "Muni:Swink.DOLA.Population-Total.Year"
TSAlias = "Swink-Muni-Population-Total"
